import {
	API_DEFAULT_FORECAST_TYPES,
	DEFAULT_DATE,
	WEATHER_API_URL,
} from '../../config'

// generate random params
// for use in forecast hook
export default function useRandomParams() {
	const randomLocations = [
		'London',
		'Berlin',
		'Oslo',
		'New York',
		'San Francisco',
		'Tokyo',
		'Paris',
		'Barcelona',
		'Rio de Janeiro',
		'Sydney',
		'Vancouver',
		'New Delhi',
		'Mumbai',
		'Melbourne',
		'Beijing',
		'Singapore',
		'Toronto',
		'Moscow',
		'Seoul',
		'Tehran',
		'Jakarta',
		'Kuala Lumpur',
		'Kathmandu',
		'Kolkata',
		'Chennai',
		'Buenos Aires',
		'Santiago',
		'Mexico City',
		'Los Angeles',
		'Minsk',
		'Brest',
		'Vilnius',
		'Kiev',
		'Gdansk',
		'Grodno',
		'Gomel',
		'Rome',
		'Bangkok',
		'Shenzhen',
		'Istanbul',
		'Bogota',
		'Lagos',
		'Cairo',
		'Lahore',
		'Dhaka',
		'Karachi',
		'Chongqing',
		'Tianjin',
		'Guangzhou',
		'Shenyang',
		'Chengdu',
		'Nanjing',
		"Xi'an",
		'Hangzhou',
		'Wuhan',
		'Harare',
		'Hanoi',
		'Ho Chi Minh City',
		'Kolkata',
		'Brisbane',
		'Perth',
		'Adelaide',
		'Auckland',
		'Cape Town',
		'Johannesburg',
		'Durban',
		'Abidjan',
		'Accra',
		'Nairobi',
		'Kampala',
		'Dar es Salaam',
		'Lusaka',
		'Maputo',
		'Windhoek',
	]
	const randomLangs = [
		'af',
		'sq',
		'ar',
		'hy',
		'az',
		'eu',
		'be',
		'bn',
		'bs',
		'bg',
		'ca',
		'ceb',
		'zh-CN',
		'zh-TW',
		'co',
		'hr',
		'cs',
		'da',
		'nl',
		'en',
		'en-GB',
		'en-US',
		'eo',
		'et',
		'fi',
		'fr',
		'fy',
		'gl',
		'ka',
		'de',
		'el',
		'gu',
		'ht',
		'ha',
		'haw',
		'he',
		'hi',
		'hmn',
		'hu',
		'is',
		'ig',
		'id',
		'ga',
		'it',
		'ja',
		'jw',
		'kn',
		'kk',
		'km',
		'ko',
		'ku',
		'ky',
		'lo',
		'la',
		'lv',
		'lt',
		'lb',
		'mk',
		'mg',
		'ms',
		'ml',
		'mt',
		'mi',
		'mr',
		'mn',
		'my',
		'ne',
		'no',
		'ny',
		'or',
		'ps',
		'fa',
		'pl',
		'pt',
		'pa',
		'ro',
		'ru',
		'sm',
		'gd',
		'sr',
		'st',
		'sn',
		'sd',
		'si',
		'sk',
		'sl',
		'so',
		'es',
		'su',
		'sw',
		'sv',
		'tg',
		'ta',
		'te',
		'th',
		'tr',
		'uk',
		'ur',
		'ug',
		'uz',
		'vi',
		'cy',
		'xh',
		'yi',
		'yo',
		'zu',
	]

	const randomLocation =
		randomLocations[Math.floor(Math.random() * randomLocations.length)]
	const randomLang =
		randomLangs[Math.floor(Math.random() * randomLangs.length)]
	const randomType =
		API_DEFAULT_FORECAST_TYPES[
			Object.keys(API_DEFAULT_FORECAST_TYPES)[
				Math.floor(
					Math.random() *
						Object.keys(API_DEFAULT_FORECAST_TYPES).length,
				)
			]
		]
	const randomApiUrl = `${WEATHER_API_URL}${randomType}.json`

	// FIXME: fix history selecting wrong day
	if (randomType === API_DEFAULT_FORECAST_TYPES.history) {
		const date = new Date()
		date.setDate(date.getDate() - Math.floor(Math.random() * 7))

		return {
			randomLocation,
			randomLang,
			randomType,
			randomDay: date.toISOString().split('T')[0],
			randomApiUrl,
		}
	} else if (randomType === API_DEFAULT_FORECAST_TYPES.forecast) {
		const date = new Date()
		date.setDate(date.getDate() + Math.floor(Math.random() * 3))

		return {
			randomLocation,
			randomLang,
			randomType,
			randomDay: date.toISOString().split('T')[0],
			randomApiUrl,
		}
	} else {
		return {
			randomLocation,
			randomLang,
			randomType,
			randomDay: DEFAULT_DATE,
			randomApiUrl,
		}
	}
}
